sudo: false
language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly

env:
  global:
    - RUST_BACKTRACE=1

before_script:
  - rustup component add clippy-preview
script:
  - cargo clippy
  - cargo build
addons:
  apt:
    packages:
      - redis-server
